gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
ewsGrpcConfig: &ewsGrpcConfig
  code: ewsGrpc
  driverName: tcp
  urlAddress: localhost:5061
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  addAccount:
    code: addAccount
  removeUserFromMailGroup:
    code: removeUserFromMailGroup
  addUserToMailGroup:
    code: addUserToMailGroup
  disable:
    code: disable
  delete:
    code: delete
  changeMailboxSize:
    code: changeMailboxSize