gatewayGrpcConfig:  &gatewayGrpcConfig
  code:  gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
dAgentGrpcConfig: &dAgentGrpcConfig
  code: dAgentGrpc
  driverName: tcp
  urlAddress: 127.0.0.1:5063
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  runRecord:
    code: runRecord