cassandradbConfig: &cassandradbConfig
  code: cassandra
  driverName: cassandra
  urlAddress: 127.0.0.1
  dbName: mate_agent
gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
excelGrpcConfig: &excelGrpcConfig
  code: excelGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5052
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  excel:
    code: excel
    logDataConfig: &logDataConfig
      code: logData
      dataStoreConfig: *cassandradbConfig
  copy:
    code: copy
  paste:
    code: paste
  createPivot:
    code: createPivot
  excelToCsv:
    code: excelToCsv
  vlookup:
    code: vlookup
  readSheet:
    code: readSheet
