gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
adGrpcConfig: &adGrpcConfig
  code: adGrpc
  driverName: tcp
  urlAddress: localhost:5053
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  connect:
    code: connect
  createUser:
    code: createUser
  disableUser:
    code: disableuser
  updateUser:
    code: updateuser
