gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
servicedeskplusGrpcConfig: &servicedeskplusGrpcConfig
  code: servicedeskGrpc
  driverName: tcp
  urlAddress: localhost:5056
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  addRequest:
    code: addRequest
  viewAllRequest:
    code: viewAllRequest
  viewRequest:
    code: viewRequest
  updateRequest:
    code: updateRequest
  getMethod:
    code: getMethod
  postMethod:
    code: postMethod
  putMethod:
    code: putMethod
  deleteMethod:
    code: deleteMethod
