gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
databaseGrpcConfig: &databaseGrpcConfig
  code: databaseGrpc
  driverName: tcp
  urlAddress: localhost:5055
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  connect:
    code: connect
  select:
    code: select
  insertUpdate:
    code: insertUpdate
  delete:
    code: delete
  disconnect:
    code: disconnect
