gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
pdfGrpcConfig: &pdfGrpcConfig
  code: pdfGrpc
  driverName: tcp
  urlAddress: localhost:5054
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  extractImage:
    code: extractImage