gatewayGrpcConfig: &gatewayGrpcConfig
  code: gatewayGrpc
  driverName: tcp
  urlAddress: 0.0.0.0:5051
fileandfolderGrpcConfig: &fileandfolderGrpcConfig
  code: fileandfolderGrpc
  driverName: tcp
  urlAddress: localhost:5058
zapConfig: &zapConfig
  code: zap
  level: debug
  enableCaller: true
logrusConfig: &logrusConfig
  code: logrus
  level: debug
  enableCaller: false
logConfig: *zapConfig
useCaseConfig:
  copyFile:
    code: copyFile
  createFile:
    code: createFile
  deleteFile:
    code: deleteFile
  copyFolder:
    code: copyFolder
  createFolder:
    code: createFolder
  deleteFolder:
    code: deleteFolder
  moveFolder:
    code: moveFolder
  moveFile:
    code: moveFile
